name: build & push

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest
    
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: docker build -t recc .

      - name: install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: authenticate with container registry 
        run: doctl registry login --expiry-seconds 600

      - name: Tag image 
        run:
          docker tag recc registry.digitalocean.com/recc-registry/recc

      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/recc-registry/recc
