name: pull requests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  unit-tests:
    name: unit tests
    uses: ./.github/workflows/tests.yml

  deploy:
    name: deploy build
    uses: ./.github/workflows/build.yml
