name: unit tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - run: go version

      - name: get dependencies
        run: go mod download

      - name: run tests
        run: go test
